Repository fugue-project/fugue, pull requests merged in 2021-05, with the labels that each got.

#198 simplify schema, make save_df consistent for avro and increase coverage
  fugue/_utils/io.py
  tests/fugue/utils/test_io.py
  tests/fugue_spark/utils/test_io.py
Labels: unit test

#199 hotfix: avro dependency
  RELEASE.md
  fugue/_utils/io.py
  fugue_version/__init__.py
Labels: HOTFIX, bug

#208 add back head for DaskDataFrame
  ._devcontainer/devcontainer.json
  fugue_dask/dataframe.py
  setup.py
Labels: dask, enhancement

#207 Update assert_or_throw
  .pylintrc
  Makefile
  fugue/_utils/interfaceless.py
  fugue/_utils/misc.py
  fugue/collections/partition.py
  fugue/dataframe/dataframe.py
  fugue/dataframe/dataframe_iterable_dataframe.py
  fugue/dataframe/dataframes.py
  fugue/dataframe/pandas_dataframe.py
  fugue/dataframe/utils.py
  fugue/execution/execution_engine.py
  fugue/execution/factory.py
  fugue/execution/native_execution_engine.py
  fugue/extensions/_utils.py
  fugue/rpc/base.py
  fugue/workflow/_checkpoint.py
  fugue/workflow/_tasks.py
  fugue/workflow/module.py
  fugue/workflow/workflow.py
  fugue_dask/_io.py
  fugue_dask/dataframe.py
  fugue_dask/execution_engine.py
  fugue_spark/_utils/convert.py
  fugue_spark/execution_engine.py
  fugue_sql/_utils.py
  fugue_sql/_visitors.py
  fugue_sql/workflow.py
Labels: refactoring

#209 release 0.5.6
  .devcontainer/devcontainer.json
  RELEASE.md
  fugue_notebook/__init__.py
  fugue_spark/_utils/convert.py
  fugue_spark/dataframe.py
Labels: behavior change, enhancement
