Repository fugue-project/fugue, pull requests merged in 2021-04, with the labels that each got.

#187 fix dataframe print slow
  fugue/dataframe/pandas_dataframe.py
  fugue_dask/dataframe.py
  setup.py
Labels: bug, core feature

#189 add jupterlab option
  fugue_notebook/__init__.py
Labels: notebook

#179 Add avro io
  .github/workflows/test37.yml
  .github/workflows/test38.yml
  Makefile
  fugue/_utils/io.py
  fugue_spark/_utils/io.py
  requirements.txt
  tests/fugue/utils/test_io.py
  tests/fugue_spark/utils/test_io.py
Labels: core feature
